name: pr

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test molnctl setup
        uses: ./
        with:
          api-token-client-id: ${{ secrets.MOLNETT_CLIENT_ID }}
          api-token-client-secret: ${{ secrets.MOLNETT_CLIENT_SECRET }}
          default-org: molnett
      - name: Check molnctl usage
        run: molnctl orgs list
      - name: Cleanup
        run: rm -r ~/.config/molnett
